const fakeData = [
    {
        title: "Complete React.js Bootcamp",
        Id: 3201,
        price: 150,
        ratings: 4.50,
        duration: 35.00,
        lactures: 32,
        courseImg: "",
        author: "Michel Clark",
        authorImg: "",
        authorExp: 7,
        authorSchool: "Jhons Hopkins University",
        authorStudyField: "Computer Science & Engineering",
        role: "Teacher"
    },
    {
        title: "Complete Node.js Bootcamp",
        Id: 3202,
        price: 170,
        ratings: 5.00,
        duration: 40.00,
        lactures: 25,
        courseImg: "",
        author: "Anny Brown",
        authorImg: "",
        authorExp: 10,
        authorSchool: "New York Science University",
        authorStudyField: "Computer Science & Engineering",
        role: "Teacher"
    },

    {
        title: "Responsive Web Design",
        Id: 3203,
        price: 90,
        ratings: 4.00,
        duration: 40,
        lactures: 12,
        courseImg: "",
        author: "Ricky Pointing",
        authorImg: "",
        authorExp: 3,
        authorSchool: "Hello Melbourne University",
        authorStudyField: "Software Enginnering & Programming School",
        role: "Guest Teacher"
    },
    {
        title: "Advance Image Editing",
        Id: 3204,
        price: 130,
        ratings: 4.20,
        duration: 35.10,
        lactures: 12,
        courseImg: "",
        author: "Stive Morkel",
        authorImg: "",
        authorExp: 6,
        authorSchool: "Florida State University",
        authorStudyField: "Applied Graphical Design",
        role: "Teacher"
    },
    {
        title: "Mastering In Logo Design",
        Id: 3205,
        price: 220,
        ratings: 5.00,
        duration: 47.40,
        lactures: 38,
        courseImg: "",
        author: "Mike Jonson",
        authorImg: "",
        authorExp: 9,
        authorSchool: "Paric Mordan Design University",
        authorStudyField: "Applied Graphical Design",
        role: "Teacher"
    },
    {
        title: "Advance Autocad Design",
        Id: 3206,
        price: 185,
        ratings: 4.75,
        duration: 40.35,
        lactures: 33,
        courseImg: "",
        author: "Steve Nicolas",
        authorImg: "",
        authorExp: 4,
        authorSchool: "London Science University",
        authorStudyField: "Civil Enginnering",
        role: "Gust Teacher"
    },
    {
        title: "Social Media Marketing",
        Id: 3207,
        price: 165,
        ratings: 4.00,
        duration: 29.50,
        lactures: 30,
        courseImg: "",
        author: "Uonche Chang",
        authorImg: "",
        authorExp: 4,
        authorSchool: "Tokyo Business University",
        authorStudyField: "Marketing",
        role: "Teacher"
    },
    {
        title: "Digital Marketing",
        Id: 3208,
        price: 180,
        ratings: 5.00,
        duration: 42.00,
        lactures: 34,
        courseImg: "",
        author: "Avane Smith",
        authorImg: "",
        authorExp: 10,
        authorSchool: "Texas Marketing University",
        authorStudyField: "Marketing",
        role: "Guest Teacher"
    },
    {
        title: "Complete Python Bootcamp",
        Id: 3209,
        price: 170,
        ratings: 4.95,
        duration: 40.00,
        lactures: 37,
        courseImg: "",
        author: "Jak Morics",
        authorImg: "",
        authorExp: 8,
        authorSchool: "Texas Science University",
        authorStudyField: "Morden Programming",
        role: "Teacher"
    },
    {
        title: "Advance Business Communication",
        Id: 3210,
        price: 100,
        ratings: 5.00,
        duration: 22.00,
        lactures: 50,
        courseImg: "",
        author: "Md. Afjal Hussain",
        authorImg: "",
        authorExp: 12,
        authorSchool: "University of Dhaka",
        authorStudyField: "Business Communication",
        role: "Teacher"
    },

]